# Generated by Django 4.2 on 2023-06-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('seat_capacity', models.PositiveSmallIntegerField()),
                ('per_day_price', models.PositiveSmallIntegerField()),
                ('no_of_cars', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=1)),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'userprofile',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('booking_status', models.CharField(max_length=20)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.car')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental_app.userprofile')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
