# Generated by Django 4.2 on 2023-06-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
