# Generated by Django 3.2.14 on 2023-06-06 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0002_rename_car_id_booking_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_status',
        ),
    ]
