# Generated by Django 3.2.14 on 2023-06-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0003_remove_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
    ]
