# Generated by Django 3.2.14 on 2023-06-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0007_car_booking_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available_cars',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
