# Generated by Django 4.2 on 2023-06-15 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0008_car_available_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='booking_queue',
        ),
    ]
